language: node_js
node_js:
  - 10

before_install:
  - npm i -g npm@6.14.4

script: npm run build

after_success: |
    sudo pip install ghp-import && \
    ghp-import dist && \
    git push -qf https://${GITHUB_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages